import { LLMProviderManager } from '../../llm/provider-manager.js';
import { ILLMOptions } from '../../llm/provider.interface.js';

/**
 * Supported agent types in the system.
 */
export type AgentType = 'architect' | 'coder' | 'reviewer' | 'context';

/**
 * Current status of an agent.
 */
export type AgentStatus = 'idle' | 'thinking' | 'working' | 'success' | 'alert' | 'error';

export type AlertSeverity = 'info' | 'warning' | 'critical' | 'urgent';

export interface IAlert {
    id: string;
    agent: AgentType;
    severity: AlertSeverity;
    message: string;
    anchorLine?: number;
    timestamp: number;
    data?: any;
}

/**
 * Current state of an agent for UI synchronization.
 */
export interface IAgentState {
    /** Current operational status */
    status: AgentStatus;
    /** Description of the current task being performed */
    currentTask?: string;
    /** Timestamp of the last state update */
    lastUpdate: number;
    /** Target line number for spatial anchoring */
    anchorLine?: number;
    /** Why the agent was activated for this specific context */
    activationReason?: string;
    /** Estimated completion timestamp for long-running tasks */
    estimatedCompletion?: number;
    /** Whether the agent is visible in the UI (default: true) */
    visible?: boolean;
}

/**
 * Request object sent to an agent for execution.
 */
export interface IAgentRequest {
    /** The main instruction or prompt for the agent */
    prompt: string;
    /** Additional context (e.g., file contents, previous reasoning) */
    context?: string;
    /** Optional LLM parameters for this specific request */
    options?: ILLMOptions;
    /** Optional structured data to pass to the agent */
    data?: any;
}

/**
 * Response object returned by an agent after execution.
 */
export interface IAgentResponse {
    /** The final result or suggestion generated by the agent */
    result: string;
    /** The step-by-step reasoning behind the result */
    reasoning: string;
    /** Alternative solutions considered by the agent */
    alternatives?: string[];
    /** Confidence score (0.0 to 1.0) */
    confidence: number;
    /** Optional structured data returned by the agent */
    data?: any;
}

/**
 * Core interface that all AI agents must implement.
 */
export interface IAgent {
    /** Unique identifier for the agent (e.g., 'coder') */
    readonly name: AgentType;
    /** Human-readable name for display in the UI */
    readonly displayName: string;
    /** Emoji or icon identifier for the agent */
    readonly icon: string;

    /**
     * Initializes the agent with the necessary dependencies.
     * @param llmManager The manager for LLM provider access
     */
    initialize(llmManager: LLMProviderManager): void;

    /**
     * Executes a request and returns a response with reasoning.
     * @param request The request containing the prompt and context
     */
    execute(request: IAgentRequest): Promise<IAgentResponse>;

    /**
     * Returns the current state of the agent.
     */
    getState(): IAgentState;
}
